name: Test Infisical Action
on: [push, workflow_dispatch]

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Test local action
              uses: ./
              with:
                  method: "universal"
                  client-id: "b84dd7c6-a773-4870-9da3-e49192844c6c"
                  client-secret: "dc89cc90bc14f48cbac676604c8ebe966318f562c966900ad142e01963f60b12"
                  domain: "https://app.infisical.com"
                  env-slug: "dev"
                  project-slug: "aaa-o7en-s5qm"
                  extra-headers: |
                      Demo-Header: Something
                      Demo-Header-2: Something-2
                      Secure-Id: 1234567890
